Update liats demo

diff --git a/bin/regress b/bin/regress
--- a/bin/regress
+++ b/bin/regress
@@ -1,64 +1,94 @@
 #!/bin/bash
 
+# Check if current path equals ~/lean, exit if not
+EXPECTED_PATH="$HOME/lean"
+CURRENT_PATH=$(pwd)
+if [[ "$CURRENT_PATH" != "$EXPECTED_PATH" ]]; then
+  echo -e "\033[0;31mScript must be run under ~/lean directory\033[0m"
+  echo -e "\033[0;35mCurrent path: $CURRENT_PATH; Expected path: $EXPECTED_PATH\033[0m"
+  exit 0
+fi
+
 ### Run regression testings under the folder regress ###
 
 if [ -z "$1" ]; then
-  echo "Please specify regression testing group/dir name or ALL to test all groups! e.g. ScalpNQ, ALL"
+  echo "Please specify a test account! e.g. LiqunTest, CongTest"
+  exit 1
+fi
+if [ -z "$2" ]; then
+  echo "Please specify a test group/dir name under or ALL! e.g. ScalpNQ, ALL"
   exit 1
 fi
 
-GROUP_NAME=$1
+ACCOUNT=$1
+GROUP_NAME=$2
 # Remove the last slash /
+if [[ $ACCOUNT == */ ]]; then
+  ACCOUNT=${ACCOUNT////}
+fi
 if [[ $GROUP_NAME == */ ]]; then
   GROUP_NAME=${GROUP_NAME////}
-  # GROUP_NAME=$(echo "$GROUP_NAME" | sed 's/.$//')
 fi
 
 echo "Regression testing ${GROUP_NAME}..."
 
 MAIN_CODE=main.py
-MAIN_CODE_BAK=main.py.bak
+CONFIG_FILE=config.json
 
 SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
 REGRESS_DIR=$(dirname "${SCRIPT_DIR}")/regress
+LIVE_DIR=$(dirname "${SCRIPT_DIR}")/live
 PROJECT_DIR=$(dirname "${REGRESS_DIR}")
-PROJECT_NAME=$(basename "${PROJECT_DIR}")
+ACCOUNT_CONFIG="${LIVE_DIR}"/${ACCOUNT}
+ACCOUNT_PROJECT="$(dirname "${PROJECT_DIR}")"/${ACCOUNT}
 REPORT_FILE="${REGRESS_DIR}"/report.txt
 
-# Always use llc for backtest!
-QC_USER=llc
+if [ ! -d "${ACCOUNT_CONFIG}" ]; then
+  echo "Directory ${ACCOUNT_CONFIG} DOES NOT exists!"
+  exit 2
+fi
+
+# Load account credentials/keys
+# shellcheck disable=SC1090
+source ~/lean/secret/"${ACCOUNT}".key
 
 # Login QuantConnect user if required
 if [ -n "${QC_USER}" ]; then
   source "${SCRIPT_DIR}"/login "${QC_USER}"
 fi
 
-# Back to lean home dir
+# Go back to lean home dir
 cd "${PROJECT_DIR}"/.. || exit
 
-cp "${PROJECT_DIR}"/${MAIN_CODE} "${PROJECT_DIR}"/${MAIN_CODE_BAK}
+# Sync to live project dir
+rsync -a --delete --exclude-from="${PROJECT_DIR}"/.leanignore "${PROJECT_DIR}"/ "${ACCOUNT_PROJECT}"/
+
+# Copy over main/config files
+cp "${ACCOUNT_CONFIG}"/${MAIN_CODE} "${ACCOUNT_PROJECT}"/${MAIN_CODE}
+cp "${ACCOUNT_CONFIG}"/${CONFIG_FILE} "${ACCOUNT_PROJECT}"/${CONFIG_FILE}
+
 
 keywords=()
 keywords+=("│ Return                      │")
 keywords+=("│ Unrealized                 │")
 keywords+=("│ Total Orders               │")
 keywords+=("│ Drawdown                   │")
+MATCHED=0
 for TEST_DIR in "${REGRESS_DIR}"/*; do
   if [[ -d ${TEST_DIR} && ("${GROUP_NAME}" == "ALL" || $(basename "${TEST_DIR}") == "${GROUP_NAME}") ]]; then
-    for TEST_FILE in "${TEST_DIR}"/*.txt; do
-      echo "Backtesting ${TEST_FILE}..."
-      cp "${TEST_FILE}" "${PROJECT_DIR}"/${MAIN_CODE}
+    ((MATCHED++))
+    for TEST_FILE in "${TEST_DIR}"/*.py; do
+      echo "----------------------------------------"
+      echo -e "\033[0;35mBacktesting ${TEST_FILE}...\033[0m"
+      cp "${TEST_FILE}" "${ACCOUNT_PROJECT}"/${MAIN_CODE}
       # Run backtest on project
-      lean cloud backtest "${PROJECT_NAME}" --push --name "$(basename "${TEST_FILE}")" | tee "${REPORT_FILE}"
+      lean cloud backtest "${ACCOUNT}" --push --name "$(basename "${TEST_FILE}")" | tee "${REPORT_FILE}"
       # Start comparing results
       for keyword in "${keywords[@]}"; do
         TEST_LINE=$(grep -F -m 1 "${keyword}" "${TEST_FILE}")
         REPORT_LINE=$(grep -F -m 1 "${keyword}" "${REPORT_FILE}")
         if [[ "${TEST_LINE}" != "${REPORT_LINE}" ]]; then
-          echo -e "!!!FAILED TO MATCH: \n${TEST_LINE} \n${REPORT_LINE}"
-          # Restore and clean up
-          cp "${PROJECT_DIR}"/${MAIN_CODE_BAK} "${PROJECT_DIR}"/${MAIN_CODE}
-          rm "${PROJECT_DIR}"/${MAIN_CODE_BAK}
+          echo -e "\033[0;31m!!!FAILED TO MATCH: \n${TEST_LINE} \n${REPORT_LINE}\033[0m"
           rm -f "${REPORT_FILE}"
           exit 3
         fi
@@ -67,11 +97,14 @@ for TEST_DIR in "${REGRESS_DIR}"/*; do
   fi
 done
 
+if [[ ${MATCHED} -eq 0 ]]; then
+  echo -e "\033[0;31mError: No matching test files found for group: ${GROUP_NAME}\033[0m"
+  exit 4
+fi
+
 echo "Completed regression testing successfully."
 
 # Restore and clean up
-cp "${PROJECT_DIR}"/${MAIN_CODE_BAK} "${PROJECT_DIR}"/${MAIN_CODE}
-rm "${PROJECT_DIR}"/${MAIN_CODE_BAK}
 rm -f "${REPORT_FILE}"
 
 # Login back to llc
